#!/usr/bin/env bash
set -e
set -u
set -o pipefail
IFS=''

BIN_C_DIR="${0%/*}"
BIN_C_DIR="${BIN_C_DIR:-.}"

(cd -- "$BIN_C_DIR" && { [[ -x ./out/bin-c ]] || ./build release; })

"$BIN_C_DIR"/out/bin-c "$@"
